// Import CSS for Vite processing
import '../css/articles.css';

// Auto-generated articles data - DO NOT EDIT MANUALLY
// This file is automatically generated by scripts/auto-register-articles.js
// To modify articles, edit the HTML files in private_html/articles/

const articles = [
  {
    "id": 824,
    "title": "Building Better Claude Code Workflows with CC-Commands",
    "excerpt": "Discover how the CC-Commands repository solves the pain points of managing custom Claude Code commands across multiple projects with elegant automation and intelligent synchronization.",
    "category": "ai",
    "date": "2025-07-18",
    "slug": "claude-code-custom-commands-cc-commands"
  },
  {
    "id": 12,
    "title": "Fedora 42: The Revolutionary Linux Release That Changes Everything",
    "excerpt": "Discover the groundbreaking features of Fedora 42, including KDE Plasma promotion to full edition status, the revolutionary COSMIC desktop environment, and the modernized Anaconda WebUI installer that transforms Linux computing.",
    "category": "infrastructure",
    "date": "2025-07-18",
    "slug": "fedora-42-breakthrough-features"
  },
  {
    "id": 459,
    "title": "Managing Legacy PHP: From Technical Debt to Modern Architecture",
    "excerpt": "Practical strategies for transforming legacy PHP codebases into maintainable, modern systems without breaking production",
    "category": "php",
    "date": "2025-01-15",
    "slug": "legacy-php-modernization"
  },
  {
    "id": 690,
    "title": "Ansible Automation for PHP Infrastructure",
    "excerpt": "Building robust, repeatable infrastructure deployment pipelines using Ansible for PHP applications",
    "category": "php",
    "date": "2025-01-10",
    "slug": "ansible-php-infrastructure"
  },
  {
    "id": 656,
    "title": "Proxmox vs Cloud: Why Private Infrastructure Wins",
    "excerpt": "Real-world comparison of Proxmox private cloud infrastructure versus public cloud solutions for PHP applications",
    "category": "php",
    "date": "2025-01-05",
    "slug": "proxmox-vs-cloud"
  },
  {
    "id": 5,
    "title": "High-Performance PHP: Optimization Strategies",
    "excerpt": "Proven techniques for optimizing PHP applications to handle high-turnover, high-complexity scenarios",
    "category": "php",
    "date": "2024-12-28",
    "slug": "high-performance-php"
  },
  {
    "id": 155,
    "title": "MySQL Performance Tuning for Complex PHP Applications",
    "excerpt": "Database optimization strategies specifically tailored for bespoke PHP systems with complex queries",
    "category": "php",
    "date": "2024-12-20",
    "slug": "mysql-performance-php"
  },
  {
    "id": 671,
    "title": "Building Scalable Backend APIs with Modern PHP",
    "excerpt": "Architectural patterns and best practices for creating robust, scalable backend systems using modern PHP",
    "category": "php",
    "date": "2024-12-15",
    "slug": "scalable-php-apis"
  },
  {
    "id": 675,
    "title": "AI-Enhanced PHP Development: Tools and Workflows",
    "excerpt": "How to leverage AI tools like GitHub Copilot and OpenAI APIs to boost PHP development efficiency without compromising quality",
    "category": "php",
    "date": "2024-12-10",
    "slug": "ai-enhanced-php-development"
  }
];

class ArticleManager {
  constructor() {
    this.articles = articles;
    this.filteredArticles = [...this.articles];
    this.currentCategory = 'all';
    this.searchTerm = '';
    this.init();
  }

  init() {
    this.setupEventListeners();
    this.renderArticles();
    this.hideLoadingIndicator();
  }

  setupEventListeners() {
    const searchInput = document.getElementById('articleSearch');
    if (searchInput) {
      searchInput.addEventListener('input', window.appUtils.debounce(e => {
        this.searchTerm = e.target.value.toLowerCase();
        this.filterArticles();
      }, 300));
    }

    document.querySelectorAll('.filter-btn').forEach(btn => {
      btn.addEventListener('click', e => {
        this.handleCategoryFilter(e.target);
      });
    });
  }

  handleCategoryFilter(button) {
    document.querySelectorAll('.filter-btn').forEach(btn => {
      btn.classList.remove('active');
    });
    button.classList.add('active');
    this.currentCategory = button.dataset.category;
    this.filterArticles();
  }

  filterArticles() {
    this.filteredArticles = this.articles.filter(article => {
      const categoryMatch = this.currentCategory === 'all' || article.category === this.currentCategory;
      const searchMatch = this.searchTerm === '' || 
        article.title.toLowerCase().includes(this.searchTerm) ||
        article.excerpt.toLowerCase().includes(this.searchTerm);
      return categoryMatch && searchMatch;
    });
    this.renderArticles();
  }

  renderArticles() {
    const grid = document.getElementById('articlesGrid');
    const noResults = document.getElementById('noResults');
    
    if (!grid) return;
    
    if (this.filteredArticles.length === 0) {
      grid.style.display = 'none';
      if (noResults) noResults.style.display = 'block';
      return;
    }
    
    grid.style.display = 'grid';
    if (noResults) noResults.style.display = 'none';
    
    grid.innerHTML = this.filteredArticles.map(article => this.createArticleCard(article)).join('');
    
    // Animate articles
    requestAnimationFrame(() => {
      grid.querySelectorAll('.article-card').forEach((card, index) => {
        setTimeout(() => {
          card.style.opacity = '1';
          card.style.transform = 'translateY(0)';
        }, index * 50);
      });
    });
  }

  createArticleCard(article) {
    const date = new Date(article.date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
    
    return `
      <article class="article-card" style="opacity: 0; transform: translateY(20px);">
        <div class="article-meta">
          <span class="article-category ${article.category}">${article.category}</span>
          <time>${date}</time>
        </div>
        <a href="/articles/${article.slug}.html" class="article-title">${article.title}</a>
        <p class="article-excerpt">${article.excerpt}</p>
        <a href="/articles/${article.slug}.html" class="article-read-more">
          Read more →
        </a>
      </article>
    `;
  }

  hideLoadingIndicator() {
    const indicator = document.getElementById('loadingIndicator');
    if (indicator) {
      indicator.style.display = 'none';
    }
  }
}

// Initialize when DOM is ready
(function() {
  function init() {
    if (typeof window.appUtils !== 'undefined') {
      new ArticleManager();
    } else {
      setTimeout(init, 50);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
