---
- name: Install and configure PHP application
  hosts: webservers
  become: yes
  tasks:
    - name: Install PHP packages
      apt:
        name:
          - php8.2-fpm
          - php8.2-mysql
          - php8.2-curl
          - php8.2-xml
        state: present
        update_cache: yes