# VM template for PHP applications
agent: 1
boot: c
bootdisk: scsi0
cores: 4
cpu: host
memory: 8192
name: php-template
net0: virtio,bridge=vmbr0,firewall=1
numa: 0
onboot: 1
ostype: l26
scsi0: local-lvm:vm-template-disk-0,size=40G
scsihw: virtio-scsi-pci
smbios1: uuid=auto
sockets: 1
vmgenid: auto
