---
# Development tools installation and configuration
# Demonstrates modular Ansible task organization
- name: "Install essential development packages"
  ansible.builtin.dnf:
    name:
      - git
      - vim
      - neovim
      - code  # VS Code
      - python3
      - python3-pip
      - nodejs
      - npm
      - golang
      - rust
      - cargo
      - gcc
      - gcc-c++
      - make
      - cmake
      - gdb
      - curl
      - wget
      - jq
      - tree
      - htop
      - tmux
      - zsh
    state: present
  tags: ['packages', 'development']

- name: "Install GitHub CLI from official repository"
  block:
    - name: "Add GitHub CLI repository"
      ansible.builtin.yum_repository:
        name: gh-cli
        description: "GitHub CLI"
        baseurl: "https://cli.github.com/packages/rpm"
        gpgkey: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x23F3D4EA75716059"
        enabled: yes
        
    - name: "Install GitHub CLI"
      ansible.builtin.dnf:
        name: gh
        state: present
  tags: ['github', 'cli']

- name: "Create Projects directory structure"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0755'
  loop:
    - "{{ projects_dir }}"
    - "{{ projects_dir }}/personal"
    - "{{ projects_dir }}/work"
    - "{{ projects_dir }}/opensource"
  tags: ['directories', 'workspace']

- name: "Configure development environment variables"
  ansible.builtin.lineinfile:
    path: "{{ user_home }}/.bashrc"
    line: "{{ item }}"
    create: yes
    mode: '0644'
  loop:
    - "export PROJECTS_HOME={{ projects_dir }}"
    - "export EDITOR=vim"
    - "export BROWSER=firefox"
    - "alias ll='ls -alF'"
    - "alias la='ls -A'"
    - "alias l='ls -CF'"
  tags: ['environment', 'aliases']

- name: "Install Node.js development tools globally"
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop:
    - typescript
    - '@types/node'
    - eslint
    - prettier
    - nodemon
  tags: ['nodejs', 'javascript']

- name: "Install Python development tools via pip"
  ansible.builtin.pip:
    name:
      - virtualenv
      - pipenv
      - black
      - flake8
      - pytest
      - jupyter
    state: present
  tags: ['python', 'pip']