name: CI Test

on:
  push:
    branches: [main]

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI test successful"